#include "nucleo_l476rg.hpp"

/**
 * @brief Handles interrupts generated by EXTI lines 10 through 15.
 *
 * Forwards the interrupt to the NUCLEO-L476RG user-button EXTI handler.
 */
extern "C" void EXTI15_10_IRQHandler(void) {
    platform::nucleo_l476rg::detail::
        handle_user_button_exti();
}